DeLuxe/urls.py
from django.contrib import admin
from deluxeapp import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
admin.autodiscover()
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.LoginPage, name='login'),
    path('index/', views.indexPage, name='index'),
    path('tables/', views.tablesPage, name='tables'),
    path('newCargo/', views.createCargo, name='createCargo'),
    path('deleteCargo/<int:id>/', views.deleteCargo, name='deleteCargo'),
    path('updateCargo/<int:id>/', views.updateCargo, name="updateCargo"),
    path('newEmpleado/', views.createEmpleado, name="createEmpleado"),
    path('deleteEmpleado/<int:id>/', views.deleteEmpleado, name='deleteEmpleado'),
    path('updateEmpleado/<int:id>/', views.updateEmpleado, name="updateEmpleado"),
    path('Buses/', views.CrudBus.as_view(), name="Buses"),
    path('newBus/', views.createBus.as_view(), name="createBus"),
    path('updateBus/', views.UpdateCrudBus.as_view(), name="updateBus"),
    path('deleteBus/', views.DeleteCrudBus.as_view(), name="deleteBus"),
    path('asistencias/', views.asistenciasPage, name='asistencias'),
    path('newAsistencia/', views.createAsistencia, name='createAsistencia'),
    path('updateAsistencia/<int:id>/', views.updateAsistencia, name='updateAsistencia'),
    path('deleteAsistencia/<int:id>/', views.deleteAsistencia, name='deleteAsistencia'),
    path('revisar/', views.revisarPage, name='revisar'),
    path('updateRevisar/<int:id>/', views.updateRevisar, name='updateRevisar'),
    path('deleteRevisar/<int:id>/', views.deleteRevisar, name='deleteRevisar'), 
    path('inasistencias/', views.inasistenciasPage, name='inasistencias'),
    path('updateInasistencia/<int:id>/', views.updateInasistencia, name='updateInasistencia'),
    path('deleteInasistencia/<int:id>/', views.deleteInasistencia, name='deleteInasistencia'),
    path('user/', views.userPage, name='user'),
    path('logout/', views.logoutUser, name='logout'),
    path('error/', views.errorPage, name='error'),
    path('indexUser/', views.indexUserPage, name="indexUser"),
    path('misAsistencias/', views.misAsistenciasPage, name='misAsistencias'),
    path('misInasistencias/', views.misInasistenciasPage, name='misInasistencias'),
    path('misEnviadas/', views.misEnviadasPage, name='misEnviadas'),
    path('newMiasistencia/', views.createMiasistencia, name="createMiasistencia"),
    path('deleteMiasistencia/<int:id>/', views.deleteMiasistencia, name='deleteMiasistencia'),
    path('reportes/', views.reportesPage, name='reportes'),
    path('export_csv',views.export_csv, name='export_csv'),
    path('export_excel',views.export_excel, name='export_excel'),
    path('export_pdf',views.export_pdf, name='export_pdf'),
    path('pdfpage', views.pdfpage, name='pdfpage'),
    path('updateAdmin/<int:id>/', views.updateAdmin, name='updateAdmin'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

deluxeapp/models.py
from django.conf import settings
from django.db import models
from django.forms.models import model_to_dict
from django.utils import timezone
# Create your models here.
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator 



class Empleado(models.Model):
    Empleado_genero = [
        (1, 'Femenino'),
        (2, 'Masculino')
    ]

    user = models.OneToOneField(User,null=True, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=50)
    genero = models.IntegerField(null=True, blank=False, choices=Empleado_genero)
    edad = models.PositiveIntegerField(null=True, validators=[MinValueValidator(1), MaxValueValidator(100)])
    fechanacimiento = models.DateField(null=True)

    
    def __str__(self):
        return self.nombre

    
class Cargo(models.Model):
    nombre = models.CharField(max_length=50,unique=True)

    def __str__(self):
        return self.nombre



class Bus(models.Model):
    placa = models.CharField(max_length=7,unique=True)
    modelo = models.CharField(max_length=50)
    marca = models.CharField(max_length=50)

    def __str__(self):
        return self.placa



class Actividad(models.Model):
    empleado = models.ForeignKey(Empleado, on_delete=models.CASCADE)
    placa = models.CharField(max_length=7)
    fecha = models.DateField()

    def __str__(self):
        return self.id


class Asistencia(models.Model):
    Asistencia_estado = [
        (1, 'Asistencia'),
        (2, 'Inasistencia'),
        (3, 'Por Revisar')
    ]
    Empleado = models.ForeignKey(Empleado, on_delete=models.CASCADE)
    Cargo = models.ForeignKey(Cargo, on_delete=models.CASCADE)
    fecha = models.DateField()
    horaentrada = models.TimeField()
    horasalida = models.TimeField()
    estado = models.IntegerField(null=False, blank=False, choices=Asistencia_estado)


    def __str__(self):
        return str(self.id)

templates/administrador/editAdmin.html
{% load static %}
<!doctype html>
<html><head>
    <meta charset="utf-8">
    <title>De Luxe S.A.C</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}" />
    <link rel="icon" type="image/jpg" href="{% static 'images/deluxe.jpg' %}">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-style.css' %}" rel="stylesheet">
    <link href="{% static 'css/register.css' %}" rel="stylesheet">

	<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- jQuery -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

  <!-- Fengyuan Chen's Datepicker -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css" integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE=" crossorigin="anonymous" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js" integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k=" crossorigin="anonymous"></script>
    <style type="text/css">
      body {
        padding-top: 60px;
      }
    </style>

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

  	<!-- Google Fonts call. Font Used Open Sans & Raleway -->
    <link href="http://fonts.googleapis.com/css?family=Raleway:400,300" rel="stylesheet" type="text/css">
  	<link href="http://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css">
	</head>
  <body>

  	<!-- NAVIGATION MENU -->

    <div class="navbar-nav navbar-inverse navbar-fixed-top">
        <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'index' %}"><img src="{% static 'images/deluxe.jpg' %}" height="15" alt=""> DeLuxe S.A.C</a>
        </div>
          <div class="navbar-collapse collapse">
            
          </div><!--/.nav-collapse -->
        </div>
    </div>
<style>
div.col-sm-6 col-lg-6{
  text-align: center;
}
</style>
    <div class="container">
        <div class="row">

        	<div class="col-lg-offset-3 col-lg-6" style="text-align: center;">
        		<div id="register-wraper">
        		    <form id="register-form" class="form" method="post" action="">
        		        <legend>Registro de Usuario Empleado</legend>
                        {% csrf_token %}
        		    
        		        <div class="body">
        		        	<!-- first name -->
    		        		{{ form }}
        		        
        		        </div>

                    
                    <br>
        		        <div class="footer">

        		            <button type="submit" class="btn btn-success">Guardar Usuario Administrador</button>
        		        </div><br>
                    {% for message in messages %}
                        <style>
                       .alertbotonverde {
  padding: 20px;
  background-color: #379634;
  color: white;
}

.closebtnverde {
  margin-left: 15px;
  color: white;
  font-weight: bold;
  float: right;
  font-size: 22px;
  line-height: 20px;
  cursor: pointer;
  transition: 0.3s;
}

.closebtnverde:hover {
  color: black;
}
                        </style>
                        <div class="alertbotonverde">
                        <span class="closebtnverde"
                              onclick="this.parentElement.style.display='none';">&times;</span>
                    {{ message }}
                    </div>

                    {% endfor %}


                        {% if form.errors %}
<style>
.alertboton {
  padding: 20px;
  background-color: #f44336;
  color: white;
}

.closebtn {
  margin-left: 15px;
  color: white;
  font-weight: bold;
  float: right;
  font-size: 22px;
  line-height: 20px;
  cursor: pointer;
  transition: 0.3s;
}

.closebtn:hover {
  color: black;
}
</style>
                    <div class="alertboton">
                        <span class="closebtn"
                              onclick="this.parentElement.style.display='none';">&times;</span>
                    {{ form.errors }}
                    </div>
                        {% endif %}
        		    </form>


        		</div>

        	</div>

        </div>
    </div>

	<div id="footerwrap">
      	<footer class="clearfix"></footer>
      	<div class="container">
      		<div class="row">
      			<div class="col-sm-12 col-lg-12">
      			<p><img src="{% static 'images/logo.png' %}" alt=""></p>
      			<p>Empresa de Transportes De Luxe S.A.C - Copyright 2021</p>
  <script>
      $(function () {
        $("#id_fechanacimiento").datepicker({
          format: 'YYYY-mm-dd',
        });
      });
    </script>
      			</div>

      		</div><!-- /row -->
      	</div><!-- /container -->
	</div><!-- /footerwrap -->
  
</body></html>

templates/administrador/editAsistencias.html
{% load static %}
<!doctype html>
<html><head>
    <meta charset="utf-8">
    <title>De Luxe S.A.C</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}" />
    <link rel="icon" type="image/jpg" href="{% static 'images/deluxe.jpg' %}">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-style.css' %}" rel="stylesheet">
    <link href="{% static 'css/register.css' %}" rel="stylesheet">

	<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css" integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE=" crossorigin="anonymous" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js" integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k=" crossorigin="anonymous"></script>
   
   <style type="text/css">
      body {
        padding-top: 60px;
      }
    </style>

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

  	<!-- Google Fonts call. Font Used Open Sans & Raleway -->
	<link href="http://fonts.googleapis.com/css?family=Raleway:400,300" rel="stylesheet" type="text/css">
  	<link href="http://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css">
	</head>
  <body>

  	<!-- NAVIGATION MENU -->

    <div class="navbar-nav navbar-inverse navbar-fixed-top">
        <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'index' %}"><img src="{% static 'images/deluxe.jpg' %}" alt=""height="15"> DeLuxe S.A.C</a>
        </div>
          <div class="navbar-collapse collapse">
            
          </div><!--/.nav-collapse -->
        </div>
    </div>
<style>
div.col-sm-6 col-lg-6{
  text-align: center;
}
</style>
    <div class="container">
        <div class="row">

        	<div class="col-lg-offset-3 col-lg-6" style="text-align: center;">
        		<div id="register-wraper">
        		    <form id="register-form" class="form" method="post" action="">
        		        <legend>Registro de Asistencia</legend>
                        {% csrf_token %}
        		    
        		        <div class="body">
        		        	<!-- first name -->
                    {% if request.user.empleado %}
                    <label for="id_Empleado">Empleado:</label>
                    {{ form.Empleado }}
    		        		
                    <label for="id_Cargo">Cargo:</label>
                    {{ form.Cargo }} 

                    <br>
                    <label for="id_fecha">Fecha:</label>
                    {{ form.fecha }}
                    <label for="id_horaentrada">Hora de Entrada:</label>
                    {{ form.horaentrada }}
                    <label for="id_horasalida">Hora de Salida:</label>
                    {{ form.horasalida }}
                    <label for="id_estado">Estado:</label>
                    <select required id="id_estado" name="estado" class="form-control">
                    <option value selected>Seleccione Estado</option>
                    <option value="3">Por revisar</option>
                    </select>
                    
                    

        		        {% endif %}
        		        </div>

                    
                    <br>
        		        <div class="footer">

        		            <button type="submit" class="btn btn-success">Guardar Asistencia</button>
        		        </div><br>
                    {% for message in messages %}
                        <style>
                       .alertbotonverde {
  padding: 20px;
  background-color: #379634;
  color: white;
}

.closebtnverde {
  margin-left: 15px;
  color: white;
  font-weight: bold;
  float: right;
  font-size: 22px;
  line-height: 20px;
  cursor: pointer;
  transition: 0.3s;
}

.closebtnverde:hover {
  color: black;
}
                        </style>
                        <div class="alertbotonverde">
                        <span class="closebtnverde"
                              onclick="this.parentElement.style.display='none';">&times;</span>
                    {{ message }}
                    </div>

                    {% endfor %}


                        {% if form.errors %}
<style>
.alertboton {
  padding: 20px;
  background-color: #f44336;
  color: white;
}

.closebtn {
  margin-left: 15px;
  color: white;
  font-weight: bold;
  float: right;
  font-size: 22px;
  line-height: 20px;
  cursor: pointer;
  transition: 0.3s;
}

.closebtn:hover {
  color: black;
}
</style>
                    <div class="alertboton">
                        <span class="closebtn"
                              onclick="this.parentElement.style.display='none';">&times;</span>
                    {{ form.errors }}
                    </div>
                        {% endif %}
        		    </form>


        		</div>

        	</div>

        </div>
    </div>

	<div id="footerwrap">
      	<footer class="clearfix"></footer>
      	<div class="container">
      		<div class="row">
      			<div class="col-sm-12 col-lg-12">
      			<p><img src="{% static 'images/logo.png' %}" alt=""></p>
      			<p>Empresa de Transportes De Luxe S.A.C - Copyright 2021</p>
      			</div>

      		</div><!-- /row -->
      	</div><!-- /container -->
	</div><!-- /footerwrap -->
     <script>
    $(function () {
        $("#id_fecha").datepicker({
          format: 'YYYY-mm-dd',
        });
      });
  </script>
   <script>
    $(function () {
      $("#id_horaentrada").clockpicker({
          language: 'es',
          autoclose:true,
          format: 'HH:mm'
      });
    });
  </script>
  <script>
    $(function () {
      $("#id_horasalida").clockpicker({
          language: 'es',
          autoclose:true,
          format: 'HH:mm'
      });
    });
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/clockpicker/0.0.7/jquery-clockpicker.min.js" integrity="sha512-x0qixPCOQbS3xAQw8BL9qjhAh185N7JSw39hzE/ff71BXg7P1fkynTqcLYMlNmwRDtgdoYgURIvos+NJ6g0rNg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/clockpicker/0.0.7/bootstrap-clockpicker.css" integrity="sha512-BB0bszal4NXOgRP9MYCyVA0NNK2k1Rhr+8klY17rj4OhwTmqdPUQibKUDeHesYtXl7Ma2+tqC6c7FzYuHhw94g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
   </body></html>

templates/administrador/editAsistenciasAdmin.html
{% load static %}
<!doctype html>
<html><head>
    <meta charset="utf-8">
    <title>De Luxe S.A.C</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}" />
    <link rel="icon" type="image/jpg" href="{% static 'images/deluxe.jpg' %}">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-style.css' %}" rel="stylesheet">
    <link href="{% static 'css/register.css' %}" rel="stylesheet">

	<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css" integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE=" crossorigin="anonymous" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js" integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k=" crossorigin="anonymous"></script>
   
   <style type="text/css">
      body {
        padding-top: 60px;
      }
    </style>

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

  	<!-- Google Fonts call. Font Used Open Sans & Raleway -->
	<link href="http://fonts.googleapis.com/css?family=Raleway:400,300" rel="stylesheet" type="text/css">
  	<link href="http://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css">
	</head>
  <body>

  	<!-- NAVIGATION MENU -->

    <div class="navbar-nav navbar-inverse navbar-fixed-top">
        <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'index' %}"><img src="{% static 'images/deluxe.jpg' %}" alt=""height="15"> DeLuxe S.A.C</a>
        </div>
          <div class="navbar-collapse collapse">
            
          </div><!--/.nav-collapse -->
        </div>
    </div>
<style>
div.col-sm-6 col-lg-6{
  text-align: center;
}
</style>
    <div class="container">
        <div class="row">

        	<div class="col-lg-offset-3 col-lg-6" style="text-align: center;">
        		<div id="register-wraper">
        		    <form id="register-form" class="form" method="post" action="">
        		        <legend>Registro de Asistencia</legend>
                        {% csrf_token %}
        		    
        		        <div class="body">
        		        	<!-- first name -->
                    {% if request.user.is_staff %}
                        {{form}}
                    
        		        {% endif %}
        		        </div>

                    
                    <br>
        		        <div class="footer">

        		            <button type="submit" class="btn btn-success">Guardar Asistencia</button>
        		        </div><br>
                    {% for message in messages %}
                        <style>
                       .alertbotonverde {
  padding: 20px;
  background-color: #379634;
  color: white;
}

.closebtnverde {
  margin-left: 15px;
  color: white;
  font-weight: bold;
  float: right;
  font-size: 22px;
  line-height: 20px;
  cursor: pointer;
  transition: 0.3s;
}

.closebtnverde:hover {
  color: black;
}
                        </style>
                        <div class="alertbotonverde">
                        <span class="closebtnverde"
                              onclick="this.parentElement.style.display='none';">&times;</span>
                    {{ message }}
                    </div>

                    {% endfor %}


                        {% if form.errors %}
<style>
.alertboton {
  padding: 20px;
  background-color: #f44336;
  color: white;
}

.closebtn {
  margin-left: 15px;
  color: white;
  font-weight: bold;
  float: right;
  font-size: 22px;
  line-height: 20px;
  cursor: pointer;
  transition: 0.3s;
}

.closebtn:hover {
  color: black;
}
</style>
                    <div class="alertboton">
                        <span class="closebtn"
                              onclick="this.parentElement.style.display='none';">&times;</span>
                    {{ form.errors }}
                    </div>
                        {% endif %}
        		    </form>


        		</div>

        	</div>

        </div>
    </div>

	<div id="footerwrap">
      	<footer class="clearfix"></footer>
      	<div class="container">
      		<div class="row">
      			<div class="col-sm-12 col-lg-12">
      			<p><img src="{% static 'images/logo.png' %}" alt=""></p>
      			<p>Empresa de Transportes De Luxe S.A.C - Copyright 2021</p>
      			</div>

      		</div><!-- /row -->
      	</div><!-- /container -->
	</div><!-- /footerwrap -->
     <script>
    $(function () {
        $("#id_fecha").datepicker({
          format: 'YYYY-mm-dd',
        });
      });
  </script>
   <script>
    $(function () {
      $("#id_horaentrada").clockpicker({
          language: 'es',
          autoclose:true,
          format: 'HH:mm'
      });
    });
  </script>
  <script>
    $(function () {
      $("#id_horasalida").clockpicker({
          language: 'es',
          autoclose:true,
          format: 'HH:mm'
      });
    });
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/clockpicker/0.0.7/jquery-clockpicker.min.js" integrity="sha512-x0qixPCOQbS3xAQw8BL9qjhAh185N7JSw39hzE/ff71BXg7P1fkynTqcLYMlNmwRDtgdoYgURIvos+NJ6g0rNg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/clockpicker/0.0.7/bootstrap-clockpicker.css" integrity="sha512-BB0bszal4NXOgRP9MYCyVA0NNK2k1Rhr+8klY17rj4OhwTmqdPUQibKUDeHesYtXl7Ma2+tqC6c7FzYuHhw94g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
   </body></html>

templates/administrador/pdf-output.html
{% load static %}
<!doctype html>
<html>
<head>
<meta charset='UTF-8'/>
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>PDF Output</title>
<style>
@page{
    size: "A4";
    margin: 2.5cm 1.5cm 3.5cm 1.5cm;

    @top-center{
        content: "DeLuxe Perú";
    }

    @bottom-right{
        content: "Page " counter(page) " of " counter(pages);
    }
}
</style>
</head>
<body>
<img src="https://ii.ct-stc.com/3/logos/empresas/2019/05/14/24533c72b9fc46418918164026928thumbnail.gif"/>

<h2>Lista de Reportes</h2>
<table class="table">
<thead class="thead">
<tr>
<th>ID</th>
<th>Empleado</th>
<th>Cargo</th>
<th>Fecha</th>
<th>Hora Entrada</th>
<th>Hora Salida</th>
<th>Estado</th>
</tr>
</thead>
<tbody>
{% for reporte in reportes %}
<tr>
<td>{{reporte.id}}</td>
<td>{{reporte.Empleado}}</td>
<td>{{reporte.cargo}}</td>
<td>{{reporte.fecha}}</td>
<td> {{reporte.horaentrada}}</td>
<td> {{reporte.horasalida}}</td>
<td>{{reporte.estado}}</td>
</tr>
{% endfor %}
<tr>
<td> Total </td>
<td> {{ total }} </td>
</tr>
</tbody>
</table>

</body>
</html>